//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIP.Models.Contexto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postulantes
    {
        public int IdPostulante { get; set; }
        public string DatosPostulante { get; set; }
        public string DNI { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Telefono { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Especialidades Especialidades { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
